### ISSUE TITLE
Support for cover image.

### ISSUE THREAD

**Issue by dismine** [slonopotamus/asciidoctor-fb2#19]
Hi.

Is there support for a cover image? Calibre shows a strange icon with a question mark instead of a cover image for the fb2 version but works in the case of epub.

![missing cover](https://user-images.githubusercontent.com/6575331/100193452-7dac1d00-2efc-11eb-86a4-5739e67dc6da.png)

**Comment by slonopotamus** [comment]
Cover image does work, see [cover.adoc](https://github.com/slonopotamus/asciidoctor-fb2/tree/master/spec/fixtures) test book:

```adoc
= Book with cover
:front-cover-image: wolpertinger.jpg
```

What image format do you use? I had success with PNG and JPEG.

**Comment by slonopotamus** [comment]
Okay, I see the problem. asciidoctor-fb2 does not fill `content-type` attribute for images.

**Comment by dismine** [comment]
Yes, your file works for me too. In my case I have a png file.

But a path to cover image in my case is different.

Here is how I define a cover image in my book.
```
= Book with cover
:front-cover-image: image:images/wolpertinger.jpg
```

**Comment by slonopotamus** [comment]
```
:front-cover-image: image:images/wolpertinger.jpg
```

I think this is invalid syntax. It should either be (already works)

```
:front-cover-image: images/wolpertinger.jpg
```

or (I will add support for this soon):

```
:front-cover-image: image:images/wolpertinger.jpg[]
```

**Comment by dismine** [comment]
Sorry, the correct syntax in my case is

`:front-cover-image: image:images/cover-0.7.png[Front Cover]`

**Comment by slonopotamus** [comment]
I think this is fixed in v0.3.0.

**Comment by dismine** [comment]
Yes, you can close. I still have issue with Okular, but others work just fine. Thank for the quick fix!
